model_configs:
  tokenizer_path: C:/Users/USER/Desktop/T5ForSummarization/src/t5model
  model_name: t5-base
  path_to_save: 
  model_path: C:/Users/USER/Desktop/T5ForSummarization/src/t5model

training_configs:
  epochs: 20
  batch_size: 2
  eval_batch_size: 2
  reduction_factor: 0.1
  patience: 3
  optimizer: Adam
  weight_decay: 0.0
  shuflle_data: True
  evaluate_dev: True
  use_cuda: False
  betas: [0.9,0.98]
  eps: 0.000000009
  lr : 0.0003
  min_lr: 0.00000001
  fp16: False


data_configs:
  train_path: C:/Users/USER/Desktop/T5ForSummarization/data/train_df.csv
  dev_path: C:/Users/USER/Desktop/T5ForSummarization/data/test_df.csv
  prefix: 'summarize: '
  max_input_len: 512
  max_output_len: 150
  



